### ISSUE TITLE
Language switcher not working on homepage

### ISSUE THREAD

**Issue by erkage** [scottsweb/elva#1] opened 2023-08-29 18:06 UTC
Hey Scott,

On / page the SE button is not working.

**Comment by scottsweb** [comment] 2023-08-29 19:25
Thanks for the report. This is actually by design on the demo at the moment. Only one, primary language can exist at the route `/` of the site.

I imagined this to be implemented in a similar way to what you find on sites like ikea.com, where all languages are presented and one can be selected.

I have two to-dos in the readme as a reminder to re-visit this:

> [Language redirect based on browser setting](https://gitlab.com/florent_tassy/polyglot-tech-blog/-/blob/main/src/js/redirect.js)?
> Cleaner language selector

The first is to redirect based on your browser language setting, skipping the route path altogether. There will still have to be a default language in the redirect logic though.

If you have some ideas on how you might like to see this work, do let me know.

**Comment by scottsweb** [comment] 2023-12-15 20:03
Closing for now but still aim to look at ways to make this smarter as per the readme.

**Closed by scottsweb** 2023-12-15 20:03 UTC
